>>> 'Pkg.add("Orchestra")' log
INFO: Cloning cache of DecisionTree from git://github.com/bensadeghi/DecisionTree.jl.git
INFO: Cloning cache of DimensionalityReduction from git://github.com/JuliaStats/DimensionalityReduction.jl.git
INFO: Cloning cache of Orchestra from git://github.com/svs14/Orchestra.jl.git
INFO: Cloning cache of ScikitLearnBase from git://github.com/cstjean/ScikitLearnBase.jl.git
INFO: Installing BinDeps v0.4.5
INFO: Installing Conda v0.3.2
INFO: Installing DataArrays v0.3.9
INFO: Installing DataFrames v0.8.4
INFO: Installing DecisionTree v0.5.0
INFO: Installing DimensionalityReduction v0.1.1
INFO: Installing FactCheck v0.4.3
INFO: Installing FileIO v0.2.0
INFO: Installing GZip v0.2.20
INFO: Installing Iterators v0.2.0
INFO: Installing MLBase v0.6.0
INFO: Installing MacroTools v0.3.2
INFO: Installing Orchestra v0.0.5
INFO: Installing PyCall v1.7.2
INFO: Installing Reexport v0.0.3
INFO: Installing SHA v0.2.1
INFO: Installing ScikitLearnBase v0.2.0
INFO: Installing SortingAlgorithms v0.1.0
INFO: Installing StatsBase v0.11.1
INFO: Installing URIParser v0.1.6
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/free/linux-64
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.9.1
       root environment : /home/vagrant/.julia/v0.4/Conda/deps/usr  (writable)
    default environment : /home/vagrant/.julia/v0.4/Conda/deps/usr
       envs directories : /home/vagrant/.julia/v0.4/Conda/deps/usr/envs
          package cache : /home/vagrant/.julia/v0.4/Conda/deps/usr/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/vagrant/.julia/v0.4/Conda/deps/usr/condarc-julia.yml
           offline mode : False



`$ /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/conda install -y numpy`




    Traceback (most recent call last):
      File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/fetch.py", line 305, in fetch_index
        for url in urls]
      File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/fetch.py", line 234, in fetch_repodata
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff716d8bc50>: Failed to establish a new connection: [Errno -2] Name or service not known',)): https://repo.continuum.io/pkgs/free/linux-64
    

===============================[ ERROR: PyCall ]================================

LoadError: failed process: Process(setenv(`/home/vagrant/.julia/v0.4/Conda/deps/usr/bin/conda install -y numpy`,Union{ASCIIString,UTF8String}["PYTHON=","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/","PWD=/vagrant/0.4MZ","SHELL=/bin/bash","SSH_CONNECTION=10.0.2.2 36513 10.0.2.15 22","LD_LIBRARY_PATH=:/usr/local/lib/","CONDARC=/home/vagrant/.julia/v0.4/Conda/deps/usr/condarc-julia.yml","MAIL=/var/mail/vagrant","LANG=en_US.UTF-8","SHLVL=3","LOGNAME=vagrant","XDG_RUNTIME_DIR=/run/user/1000","XDG_SESSION_ID=3","OLDPWD=/home/vagrant","SSH_CLIENT=10.0.2.2 36513 22","_=/usr/bin/timeout","USER=vagrant","TERM=vt100","HOME=/home/vagrant","OPENBLAS_MAIN_FREE=1","JAVA_HOME=/usr/lib/jvm/java-7-oracle","PYTHONIOENCODING=UTF-8"]), ProcessExited(1)) [1]
while loading /home/vagrant/.julia/v0.4/PyCall/deps/build.jl, in expression starting on line 17

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: PyCall had build errors.

 - packages with build errors remain installed in /home/vagrant/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("PyCall")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated

>>> 'Pkg.test("Orchestra")' log
Julia Version 0.4.7
Commit ae26b25 (2016-09-18 16:17 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64 x86_64
Memory: 2.939289093017578 GB (880.20703125 MB free)
Uptime: 12090.0 sec
Load Avg:  1.06689453125  1.0146484375  1.01318359375
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3499 MHz     556920 s       4108 s      54893 s     479176 s         24 s
#2  3499 MHz     380899 s       1207 s      49338 s     733537 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-7-oracle
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.4
2 required packages:
 - JSON                          0.8.0
 - Orchestra                     0.0.5
20 additional packages:
 - BinDeps                       0.4.5
 - Compat                        0.9.3
 - Conda                         0.3.2
 - DataArrays                    0.3.9
 - DataFrames                    0.8.4
 - DecisionTree                  0.5.0
 - DimensionalityReduction       0.1.1
 - FactCheck                     0.4.3
 - FileIO                        0.2.0
 - GZip                          0.2.20
 - Iterators                     0.2.0
 - MLBase                        0.6.0
 - MacroTools                    0.3.2
 - PyCall                        1.7.2
 - Reexport                      0.0.3
 - SHA                           0.2.1
 - ScikitLearnBase               0.2.0
 - SortingAlgorithms             0.1.0
 - StatsBase                     0.11.1
 - URIParser                     0.1.6
INFO: Testing Orchestra
ERROR: LoadError: LoadError: PyCall not properly installed. Please run Pkg.build("PyCall")
 [inlined code] from /home/vagrant/.julia/v0.4/PyCall/src/startup.jl:45
 in anonymous at no file:0
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:333
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:333
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/PyCall/src/startup.jl, in expression starting on line 42
while loading /home/vagrant/.julia/v0.4/PyCall/src/PyCall.jl, in expression starting on line 37
ERROR: LoadError: LoadError: LoadError: Failed to precompile PyCall to /home/vagrant/.julia/lib/v0.4/PyCall.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:420
 in require at ./loading.jl:255
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:333
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:333
 in require at ./loading.jl:273
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:333
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/Orchestra/src/system.jl, in expression starting on line 4
while loading /home/vagrant/.julia/v0.4/Orchestra/src/Orchestra.jl, in expression starting on line 5
while loading /home/vagrant/.julia/v0.4/Orchestra/test/runtests.jl, in expression starting on line 4
==============================[ ERROR: Orchestra ]==============================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/Orchestra/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: Orchestra had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:257
 in _start at ./client.jl:378

>>> End of log
