>>> 'Pkg.add("PyCall")' log
INFO: Installing BinDeps v0.4.5
INFO: Installing Conda v0.3.2
INFO: Installing MacroTools v0.3.2
INFO: Installing PyCall v1.7.2
INFO: Installing SHA v0.2.1
INFO: Installing URIParser v0.1.6
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Fetching package metadata .......
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/vagrant/.julia/v0.4/Conda/deps/usr:
#
numpy                     1.10.4                   py27_2  
INFO: PyCall is using /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python (Python 2.7.12) at /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.4/Conda/deps/usr/lib/libpython2.7
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of PyCall
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("PyCall")' log
Julia Version 0.4.7
Commit ae26b25 (2016-09-18 16:17 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-98-generic #145-Ubuntu SMP Sat Oct 8 20:13:07 UTC 2016 x86_64 x86_64
Memory: 2.939289093017578 GB (509.23828125 MB free)
Uptime: 17232.0 sec
Load Avg:  1.34521484375  1.22119140625  1.13037109375
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3499 MHz     774162 s       5752 s      74146 s     687402 s        100 s
#2  3499 MHz     534697 s        418 s      65126 s    1043967 s          2 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-7-oracle
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.4
2 required packages:
 - JSON                          0.8.0
 - PyCall                        1.7.2
6 additional packages:
 - BinDeps                       0.4.5
 - Compat                        0.9.2
 - Conda                         0.3.2
 - MacroTools                    0.3.2
 - SHA                           0.2.1
 - URIParser                     0.1.6
INFO: Testing PyCall
INFO: Python version 2.7.12 from /home/vagrant/.julia/v0.4/Conda/deps/usr/lib/libpython2.7, PYTHONHOME=/home/vagrant/.julia/v0.4/Conda/deps/usr:/home/vagrant/.julia/v0.4/Conda/deps/usr
ENV[PYTHONPATH]=
ENV[PYTHONHOME]=
ENV[PYTHONEXECUTABLE]=

signal (11): Segmentation fault
unknown function (ip: 0x7f540dc37b1a)
unknown function (ip: 0x7f540da5a7ec)
unknown function (ip: 0x7f540da8e38d)
unknown function (ip: 0x7f540da8f24d)
unknown function (ip: 0x7f540da9374c)
unknown function (ip: 0x7f540da8e033)
unknown function (ip: 0x7f540da8ea10)
unknown function (ip: 0x7f540da8f24d)
unknown function (ip: 0x7f540da98191)
unknown function (ip: 0x7f540daa41ce)
unknown function (ip: 0x7f540da8dff2)
unknown function (ip: 0x7f540daab132)
unknown function (ip: 0x7f540dab8468)
unknown function (ip: 0x7f540daba1c1)
unknown function (ip: 0x7f540dabb688)
unknown function (ip: 0x7f540e187ef7)
unknown function (ip: 0x7f540e187fce)
unknown function (ip: 0x7f540e1880e4)
unknown function (ip: 0x7f540dc21094)
unknown function (ip: 0x7f540dc2165f)
unknown function (ip: 0x7f540dc217b4)
unknown function (ip: 0x7f540d89fbad)
jl_trampoline at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
roundtripeq at /home/vagrant/.julia/v0.4/PyCall/test/runtests.jl:11
jlcall_roundtripeq_22836 at  (unknown line)
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
anonymous at test.jl:92
do_test at test.jl:50
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 0x7f540d8e4266)
unknown function (ip: 0x7f540d8e35cf)
unknown function (ip: 0x7f540d8f8a5c)
unknown function (ip: 0x7f540d8f972c)
jl_load at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
include at ./boot.jl:261
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
include_from_node1 at ./loading.jl:333
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
process_options at ./client.jl:284
_start at ./client.jl:378
unknown function (ip: 0x7f540ab26e79)
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 0x401c87)
unknown function (ip: 0x40186f)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x4018b5)
===============================[ ERROR: PyCall ]================================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/PyCall/test/runtests.jl`, ProcessSignaled(11)) [0]

================================================================================
ERROR: PyCall had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:257
 in _start at ./client.jl:378

>>> End of log
