>>> 'Pkg.add("Qwt")' log
INFO: Cloning cache of Qwt from https://github.com/tbreloff/Qwt.jl.git
INFO: Installing BinDeps v0.3.20
INFO: Installing ColorTypes v0.2.0
INFO: Installing Colors v0.6.1
INFO: Installing Conda v0.1.8
INFO: Installing Dates v0.4.4
INFO: Installing FixedPointNumbers v0.1.1
INFO: Installing ImmutableArrays v0.0.11
INFO: Installing PyCall v1.2.0
INFO: Installing Qwt v0.0.1
INFO: Installing Reexport v0.0.3
INFO: Installing SHA v0.1.2
INFO: Installing URIParser v0.1.2
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
WARNING: isexecutable is deprecated as it implied that the file would actually be executable by the user; consider using `isfile` instead. see also the system man page for `access`
 in depwarn at deprecated.jl:73
 [inlined code] from deprecated.jl:913
 in _install_conda at /home/vagrant/.julia/v0.5/Conda/src/Conda.jl:119
 [inlined code] from /home/vagrant/.julia/v0.5/Conda/src/Conda.jl:142
 in anonymous at no file:0
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:401
 [inlined code] from sysimg.jl:14
 in evalfile at loading.jl:417
 in evalfile at loading.jl:417
 in anonymous at none:14
 in cd at file.jl:47
 in anonymous at none:13
 in open at iostream.jl:114
 in eval at ./boot.jl:265
 [inlined code] from ./sysimg.jl:14
 in process_options at ./client.jl:222
 in _start at ./client.jl:301
while loading /home/vagrant/.julia/v0.5/PyCall/deps/build.jl, in expression starting on line 17
Fetching package metadata: ....
Solving package specifications: ...................
# All requested packages already installed.
# packages in environment at /home/vagrant/.julia/v0.5/Conda/deps/usr:
#
numpy                     1.10.2                   py27_0    http://repo.continuum.io/pkgs/free/linux-64/numpy-1.10.2-py27_0.tar.bz2
INFO: PyCall is using /home/vagrant/.julia/v0.5/Conda/deps/usr/bin/python (Python 2.7.11) at /home/vagrant/.julia/v0.5/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.5/Conda/deps/usr/lib/libpython2.7.so
INFO: Package database updated

>>> 'Pkg.test("Qwt")' log
Julia Version 0.5.0-dev+1968
Commit e55c22a (2016-01-02 23:28 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
INFO: Testing Qwt
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.5/PyCall.ji for module PyCall.
ERROR: LoadError: InitError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named PyQt4.Qt',)

 [inlined code] from /home/vagrant/.julia/v0.5/PyCall/src/exception.jl:56
 in pyimport at /home/vagrant/.julia/v0.5/PyCall/src/PyCall.jl:302
 in __init__ at /home/vagrant/.julia/v0.5/Qwt/src/Qwt.jl:182
 in _require_from_serialized at loading.jl:165
 in require at ./loading.jl:340
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:401
 in process_options at ./client.jl:245
 in _start at ./client.jl:301
during initialization of module Qwt
while loading /home/vagrant/.julia/v0.5/Qwt/test/runtests.jl, in expression starting on line 1
=================================[ ERROR: Qwt ]=================================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.5/Qwt/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: Base.Pkg.PkgError("Qwt had test errors")
 in test at pkg/entry.jl:671
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:47
 in cd at pkg/dir.jl:31
 in test at pkg.jl:228
 in eval at ./boot.jl:265
 [inlined code] from ./sysimg.jl:14
 in process_options at ./client.jl:222
 in _start at ./client.jl:301

>>> End of log
