>>> 'Pkg.add("Qwt")' log
INFO: Cloning cache of ImmutableArrays from git://github.com/JuliaGeometry/ImmutableArrays.jl.git
INFO: Cloning cache of Qwt from git://github.com/tbreloff/Qwt.jl.git
INFO: Installing BinDeps v0.4.5
INFO: Installing ColorTypes v0.2.6
INFO: Installing Colors v0.6.7
INFO: Installing Conda v0.3.2
INFO: Installing FixedPointNumbers v0.1.6
INFO: Installing ImmutableArrays v0.0.12
INFO: Installing MacroTools v0.3.2
INFO: Installing PyCall v1.7.2
INFO: Installing Qwt v0.0.1
INFO: Installing Reexport v0.0.3
INFO: Installing SHA v0.2.1
INFO: Installing URIParser v0.1.6
INFO: Building PyCall
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.4/SHA.ji for module SHA.
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.4/BinDeps.ji for module BinDeps.
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.4/Conda.ji for module Conda.
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Fetching package metadata .......
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/vagrant/.julia/v0.4/Conda/deps/usr:
#
numpy                     1.10.4                   py27_2  
INFO: PyCall is using /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python (Python 2.7.12) at /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.4/Conda/deps/usr/lib/libpython2.7
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of Qwt
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("Qwt")' log
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-95-generic #142-Ubuntu SMP Fri Aug 12 17:00:09 UTC 2016 x86_64 x86_64
Memory: 2.4471054077148438 GB (585.2890625 MB free)
Uptime: 16811.0 sec
Load Avg:  0.9228515625  0.9833984375  0.96533203125
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3500 MHz     750373 s       2766 s      80581 s     647847 s         45 s
#2  3500 MHz     508030 s       3760 s      68677 s    1027079 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-7-oracle
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.4
2 required packages:
 - JSON                          0.7.0
 - Qwt                           0.0.1
12 additional packages:
 - BinDeps                       0.4.5
 - ColorTypes                    0.2.6
 - Colors                        0.6.7
 - Compat                        0.9.2
 - Conda                         0.3.2
 - FixedPointNumbers             0.1.6
 - ImmutableArrays               0.0.12
 - MacroTools                    0.3.2
 - PyCall                        1.7.2
 - Reexport                      0.0.3
 - SHA                           0.2.1
 - URIParser                     0.1.6
INFO: Testing Qwt
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.4/PyCall.ji for module PyCall.
ERROR: LoadError: InitError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named Qwt5',)

 [inlined code] from /home/vagrant/.julia/v0.4/PyCall/src/exception.jl:81
 in pyimport at /home/vagrant/.julia/v0.4/PyCall/src/PyCall.jl:387
 in __init__ at /home/vagrant/.julia/v0.4/Qwt/src/Qwt.jl:183
 in _require_from_serialized at loading.jl:84
 in require at ./loading.jl:267
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
during initialization of module Qwt
while loading /home/vagrant/.julia/v0.4/Qwt/test/runtests.jl, in expression starting on line 1
=================================[ ERROR: Qwt ]=================================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/Qwt/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: Qwt had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:257
 in _start at ./client.jl:378

>>> End of log
