>>> 'Pkg.add("Qwt")' log
INFO: Cloning cache of ImmutableArrays from git://github.com/JuliaGeometry/ImmutableArrays.jl.git
INFO: Cloning cache of Qwt from git://github.com/tbreloff/Qwt.jl.git
INFO: Installing BinDeps v0.4.5
INFO: Installing ColorTypes v0.2.12
INFO: Installing Colors v0.6.9
INFO: Installing Conda v0.4.0
INFO: Installing FixedPointNumbers v0.2.1
INFO: Installing ImmutableArrays v0.0.12
INFO: Installing MacroTools v0.3.2
INFO: Installing PyCall v1.7.2
INFO: Installing Qwt v0.0.1
INFO: Installing Reexport v0.0.3
INFO: Installing SHA v0.2.1
INFO: Installing URIParser v0.1.6
INFO: Building Conda
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Fetching package metadata .......
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/vagrant/.julia/v0.4/Conda/deps/usr:
#
numpy                     1.10.4                   py27_2  
INFO: PyCall is using /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python (Python 2.7.12) at /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.4/Conda/deps/usr/lib/libpython2.7
INFO: Package database updated

>>> 'Pkg.test("Qwt")' log
Julia Version 0.4.7
Commit ae26b25 (2016-09-18 16:17 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64 x86_64
Memory: 2.939289093017578 GB (564.8828125 MB free)
Uptime: 19223.0 sec
Load Avg:  0.98046875  1.01708984375  1.0390625
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3496 MHz     897150 s        403 s      84392 s     742947 s         87 s
#2  3496 MHz     565635 s       6822 s      75869 s    1195228 s          1 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-7-oracle
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.4
2 required packages:
 - JSON                          0.8.0
 - Qwt                           0.0.1
12 additional packages:
 - BinDeps                       0.4.5
 - ColorTypes                    0.2.12
 - Colors                        0.6.9
 - Compat                        0.9.3
 - Conda                         0.4.0
 - FixedPointNumbers             0.2.1
 - ImmutableArrays               0.0.12
 - MacroTools                    0.3.2
 - PyCall                        1.7.2
 - Reexport                      0.0.3
 - SHA                           0.2.1
 - URIParser                     0.1.6
INFO: Testing Qwt
ERROR: LoadError: InitError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named Qwt5',)

 [inlined code] from /home/vagrant/.julia/v0.4/PyCall/src/exception.jl:81
 in pyimport at /home/vagrant/.julia/v0.4/PyCall/src/PyCall.jl:387
 in __init__ at /home/vagrant/.julia/v0.4/Qwt/src/Qwt.jl:183
 in _include_from_serialized at loading.jl:62
 in _require_from_serialized at loading.jl:87
 in require at ./loading.jl:280
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:333
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
during initialization of module Qwt
while loading /home/vagrant/.julia/v0.4/Qwt/test/runtests.jl, in expression starting on line 1
=================================[ ERROR: Qwt ]=================================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/Qwt/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: Qwt had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:257
 in _start at ./client.jl:378

>>> End of log
