>>> 'Pkg.add("SGP4")' log
INFO: Cloning cache of SGP4 from git://github.com/crbinz/SGP4.jl.git
INFO: Installing Dates v0.4.4
INFO: Installing PyCall v0.8.2
INFO: Installing SGP4 v0.0.1
INFO: Package database updated

>>> 'Pkg.test("SGP4")' log
Julia Version 0.4.0-pre+7097
Commit c4b089f (2015-08-29 13:17 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
INFO: Testing SGP4
ERROR: LoadError: ArgumentError: SGP4 not found in path
 in require at ./loading.jl:200
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:271
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/vagrant/.julia/v0.4/SGP4/test/runtests.jl, in expression starting on line 1
================================[ ERROR: SGP4 ]=================================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/SGP4/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: SGP4 had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:753
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:284
 in _start at ./client.jl:411

>>> End of log
