>>> 'Pkg.add("SGP4")' log
INFO: Cloning cache of SGP4 from git://github.com/crbinz/SGP4.jl.git
INFO: Installing SGP4 v0.0.2
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Fetching package metadata: ....
Solving package specifications: ...................
# All requested packages already installed.
# packages in environment at /home/vagrant/.julia/v0.4/Conda/deps/usr:
#
numpy                     1.10.1                   py27_0  
INFO: PyCall is using /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python (Python 2.7.10) at /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.4/Conda/deps/usr/lib/libpython2.7.so
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of SGP4
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("SGP4")' log
Julia Version 0.4.1
Commit cbe1bee* (2015-11-08 10:33 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
INFO: Testing SGP4
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.4/PyCall.ji for module PyCall.
WARNING: requiring "Dates" in module "SGP4" did not define a corresponding module.
ERROR: LoadError: LoadError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named sgp4.io',)

 [inlined code] from /home/vagrant/.julia/v0.4/PyCall/src/exception.jl:81
 in pyimport at /home/vagrant/.julia/v0.4/PyCall/src/PyCall.jl:302
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/SGP4/src/SGP4.jl, in expression starting on line 341
while loading /home/vagrant/.julia/v0.4/SGP4/test/runtests.jl, in expression starting on line 1
================================[ ERROR: SGP4 ]=================================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/SGP4/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: SGP4 had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:257
 in _start at ./client.jl:378

>>> End of log
