>>> 'Pkg.add("SGP4")' log
INFO: Cloning cache of SGP4 from git://github.com/crbinz/SGP4.jl.git
INFO: Installing BinDeps v0.3.21
INFO: Installing Conda v0.2.3
INFO: Installing Dates v0.3.2
INFO: Installing HttpCommon v0.1.2
INFO: Installing PyCall v1.2.0
INFO: Installing SGP4 v0.0.3
INFO: Installing SHA v0.2.1
INFO: Installing URIParser v0.0.7
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Traceback (most recent call last):
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/bin/conda", line 4, in <module>
    import conda.cli
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main.py", line 46, in <module>
    from ..base.context import context
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/base/context.py", line 251, in <module>
    context = Context(SEARCH_PATH, conda, None)
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 692, in __init__
    self._add_search_path(search_path)
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 699, in _add_search_path
    return self._add_raw_data(load_file_configs(search_path))
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/_abcoll.py", line 571, in update
    for key, value in other:
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 346, in _file_yaml_loader
    assert fullpath.endswith(".yml") or fullpath.endswith("condarc"), fullpath
AssertionError: /home/vagrant/.julia/v0.3/Conda/deps/usr/condarc-julia
===============================[ ERROR: PyCall ]================================

failed process: Process(setenv(`/home/vagrant/.julia/v0.3/Conda/deps/usr/bin/conda install -y numpy`,Union(UTF8String,ASCIIString)["PYTHON=","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/","PWD=/vagrant/0.3MZ","SHELL=/bin/bash","SSH_CONNECTION=10.0.2.2 54846 10.0.2.15 22","LD_LIBRARY_PATH=:/usr/local/lib/","CONDARC=/home/vagrant/.julia/v0.3/Conda/deps/usr/condarc-julia","MAIL=/var/mail/vagrant","LANG=en_US.UTF-8","SHLVL=3","LOGNAME=vagrant","XDG_RUNTIME_DIR=/run/user/1000","XDG_SESSION_ID=3","OLDPWD=/home/vagrant","SSH_CLIENT=10.0.2.2 54846 22","_=/usr/bin/timeout","USER=vagrant","TERM=vt100","HOME=/home/vagrant","JAVA_HOME=/usr/lib/jvm/java-7-oracle","PYTHONIOENCODING=UTF-8"]), ProcessExited(1)) [1]
while loading /home/vagrant/.julia/v0.3/PyCall/deps/build.jl, in expression starting on line 17

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: PyCall had build errors.

 - packages with build errors remain installed in /home/vagrant/.julia/v0.3
 - build the package(s) and all dependencies with `Pkg.build("PyCall")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated

>>> 'Pkg.test("SGP4")' log
Julia Version 0.3.12
Commit 80aa779 (2015-10-26 12:41 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-95-generic #142-Ubuntu SMP Fri Aug 12 17:00:09 UTC 2016 x86_64 x86_64
Memory: 2.4471054077148438 GB (572.02734375 MB free)
Uptime: 17174.0 sec
Load Avg:  1.01123046875  0.92138671875  0.8671875
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3502 MHz     692943 s         20 s      81649 s     741590 s         29 s
#2  3502 MHz     489314 s       5080 s      73290 s    1058308 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-7-oracle
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.3
2 required packages:
 - JSON                          0.6.1
 - SGP4                          0.0.3
8 additional packages:
 - BinDeps                       0.3.21
 - Compat                        0.8.8
 - Conda                         0.2.3
 - Dates                         0.3.2
 - HttpCommon                    0.1.2
 - PyCall                        1.2.0
 - SHA                           0.2.1
 - URIParser                     0.0.7
INFO: Testing SGP4
ERROR: PyCall not properly installed. Please run Pkg.build("PyCall")
 in error at error.jl:21
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/vagrant/.julia/v0.3/PyCall/src/PyCall.jl, in expression starting on line 36
while loading /home/vagrant/.julia/v0.3/SGP4/src/SGP4.jl, in expression starting on line 7
while loading /home/vagrant/.julia/v0.3/SGP4/test/runtests.jl, in expression starting on line 1
================================[ ERROR: SGP4 ]=================================

failed process: Process(`/home/vagrant/julia/bin/julia /home/vagrant/.julia/v0.3/SGP4/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: SGP4 had test errors
 in error at error.jl:21
 in test at pkg/entry.jl:718
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:67
 in process_options at ./client.jl:213
 in _start at ./client.jl:354

>>> End of log
