>>> 'Pkg.add("SymPy")' log
INFO: Cloning cache of SymPy from git://github.com/jverzani/SymPy.jl.git
INFO: Installing Plots v0.5.0
INFO: Installing SymPy v0.2.34
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Fetching package metadata: ....
Solving package specifications: ...................
# All requested packages already installed.
# packages in environment at /home/vagrant/.julia/v0.4/Conda/deps/usr:
#
numpy                     1.10.2                   py27_0    http://repo.continuum.io/pkgs/free/linux-64/numpy-1.10.2-py27_0.tar.bz2
INFO: PyCall is using /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python (Python 2.7.11) at /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.4/Conda/deps/usr/lib/libpython2.7.so
INFO: Package database updated

>>> 'Pkg.test("SymPy")' log
Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
INFO: Testing SymPy
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.4/PyCall.ji for module PyCall.
ERROR: LoadError: module DataArrays not found in current path; removed orphaned cache file /home/vagrant/.julia/lib/v0.4/DataArrays.ji
 in error at ./error.jl:21
 in recompile_stale at loading.jl:457
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at loading.jl:109
 in require at loading.jl:219
 in stale_cachefile at loading.jl:441
 in recompile_stale at loading.jl:459
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:219
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/SymPy/src/SymPy.jl, in expression starting on line 129
ERROR: LoadError: LoadError: Failed to precompile SymPy to /home/vagrant/.julia/lib/v0.4/SymPy.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:384
 in require at ./loading.jl:250
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/SymPy/test/tests.jl, in expression starting on line 1
while loading /home/vagrant/.julia/v0.4/SymPy/test/runtests.jl, in expression starting on line 1
================================[ ERROR: SymPy ]================================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/SymPy/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: SymPy had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:257
 in _start at ./client.jl:378

>>> End of log
