>>> 'Pkg.add("SymPy")' log
INFO: Cloning cache of SymPy from git://github.com/jverzani/SymPy.jl.git
INFO: Installing Plots v0.4.0
INFO: Installing SymPy v0.2.30
INFO: Building PyCall
INFO: PyCall is using /usr/bin/python (Python 2.7.6) at /usr/bin/python, libpython = libpython2.7
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of SymPy
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("SymPy")' log
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
INFO: Testing SymPy
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.4/PyCall.ji for module PyCall.
[Plots.jl] Default backend: pyplot
WARNING: eval from module Plots to SymPy:    
Expr(:import, :DataFrames)::Any
  ** incremental compilation may be broken for this module **

[Plots.jl] Default backend: pyplot
ERROR: LoadError: LoadError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named mpmath',)

 [inlined code] from /home/vagrant/.julia/v0.4/PyCall/src/exception.jl:81
 in pyimport at /home/vagrant/.julia/v0.4/PyCall/src/PyCall.jl:79
 in mpmath_init at /home/vagrant/.julia/v0.4/PyCall/src/conversions.jl:659
 in call at /home/vagrant/.julia/v0.4/SymPy/src/utils.jl:12
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/vagrant/.julia/v0.4/SymPy/test/tests.jl, in expression starting on line 22
while loading /home/vagrant/.julia/v0.4/SymPy/test/runtests.jl, in expression starting on line 1
================================[ ERROR: SymPy ]================================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/SymPy/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: SymPy had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:753
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:284
 in _start at ./client.jl:411

>>> End of log
